---
title: "Ally's Clean data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load the libraries
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(here)
library(naniar)
``` 

## Load the Data
```{r message=FALSE, warning=FALSE}
asd <- readr::read_csv("ASD_meta_abundance_2.csv")
asd
```


## Tidying the Data
```{r}
asd_tidy <- asd %>% 
  pivot_longer(-Taxonomy, 
               names_to = "subject", 
               values_to = "abundance") %>% 
  separate(subject, into = c("group", "number"), sep = 1)
asd_tidy
```


## Remove unidentified bacteria
```{r}
asd_tidy2 <- asd_tidy %>% 
  filter(str_detect(Taxonomy, "Unclassified") == FALSE)
asd_tidy2
```

## Tidy up the Taxonomy column
```{r}
asd_tidy3 <- 
  asd_tidy2 %>% 
  separate(Taxonomy, into = c("genus", "species"), sep = ";")
```

## Tidy up the species and genus columns
```{r}
asd_tidy4 <-
  asd_tidy3 %>% 
  separate(genus, into = c("g", "genus"), sep = "__") %>% 
  separate(species, into = c("s", "species"), sep = "__") %>% 
  select( -g, -s)
asd_tidy4
```

## Make genus and species into factors
```{r}
asd_tidy4$genus <- as.factor(asd_tidy4$genus)
asd_tidy4$species <- as.factor(asd_tidy4$species)
```


## Break it into an ASD and TD groups
```{r}
asd_group <-
  asd_tidy4 %>% 
  filter(group == "A")
asd_group
```

```{r}
td_group <-
  asd_tidy4 %>% 
  filter(group == "B")
td_group
```

## Preliminary Analysis of TD and ASD groups
```{r}
td_group %>% 
  filter(abundance != 0) %>% 
  summarize(n_genus = n_distinct(genus), n_species = n_distinct(species))
```

```{r}
asd_group %>% 
  filter(abundance != 0) %>% 
  summarize(n_genus = n_distinct(genus), n_species = n_distinct(species))
```
```{r}
getwd()
```


## Exporting CSVs
```{r}
write.csv(asd_tidy4, file = "microbiome.csv", row.names = FALSE)
```

```{r}
write.csv(asd_group, file = "asd_group.csv", row.names = FALSE)
```

```{r}
write.csv(td_group, file = "td_group.csv", row.names = FALSE)
```

