---
title: "Tidy Attempt"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
getwd()
```

```{r}
library(tidyverse)
library(janitor)
library(here)
library(naniar)
```


```{r}
asd_microbiome <- read_csv("C:/Users/Claire Chapman/Desktop/BIS15L_Project_Group11/untidy_data/ASD meta abundance 2.csv")
```

```{r}
asd_microbiome <- janitor::clean_names(asd_microbiome)
```


```{r}
names(asd_microbiome)
```
```{r}
asd_microbiome
```

#### pivoting longer and taking out unclassified data
```{r}
asd_microbiome_longer <- asd_microbiome %>% 
  pivot_longer(-taxonomy, names_to = "condition", values_to = "abundance")%>% 
  filter(str_detect(taxonomy, "Unclassified") == FALSE)
asd_microbiome_longer
```

#### wrangling the taxonomy column into genus, species, strain
```{r}
asd_microbiome_tidy <- asd_microbiome_longer %>% 
  separate(condition, into = c("condition", "patient_id"), sep = 1) %>% 
  separate(taxonomy, into = c("genus", "species"), sep = ";s__") %>% 
  separate(genus, into = c("trash", "genus"), sep = "__") %>% 
  separate(species, into = c("species", "strain"), sep = " sp. ") %>%
  separate(species, into = c("extra_genus", "species"), sep = " ")
asd_microbiome_tidy
```


#### getting rid of extra genus/g and making a culture column

```{r}
asd_microbiome_tidy3 <- asd_microbiome_tidy %>% 
  mutate(cultured = ifelse(extra_genus == "uncultured", FALSE, TRUE)) %>% 
  select(- extra_genus, - trash)
asd_microbiome_tidy3
```

#### finding unknown species
```{r}
asd_microbiome_tidy4 <- asd_microbiome_tidy3 %>% 
  mutate(species = ifelse(species == genus, NA, species))
view(asd_microbiome_tidy4)
```

```{r}
asd_microbiome_tidy4 %>% 
  filter(species == "copri")
```


#### write
```{r}
write.csv(asd_microbiome_tidy4, file = "tidiermicrobiome.csv", row.names = FALSE)
```

