---
title: "Prelim Graphs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load library
```{r}
library(tidyverse)
library(here)
```

```{r}
getwd()
options(scipen=999)
```


```{r}
microbiome <- readr::read_csv(here("tidy_data", "microbiome.csv"))
```
```{r}
names(microbiome)
```
```{r}
view(microbiome)
```


### Number of individuals in each group
```{r}
microbiome %>% 
  group_by(group, number) %>% 
  count() %>% 
  ggplot(aes(x= group, fill = group))+
  geom_bar()+ 
  scale_fill_brewer(palette = "Accent")+
  labs(title = "Number of Individuals in Each Group", x = "Group", y = "Count")
```

### Number of observations in each group
```{r}
microbiome %>% 
  ggplot(aes(x = group, fill = group)) + 
  geom_bar()+ 
  scale_fill_brewer(palette = "Accent")+
  labs(title = "Number of Observations in Each Group", x = "Group", y = "Count") 
```
```{r}
microbiome %>% 
  select(group, genus, abundance) %>% 
  filter(group == "B", abundance > 1000) %>% 
  summarise(genera = n_distinct(genus))
```

### Most Frequent Genera
```{r}
microbiome %>% 
  select(group, genus, abundance) %>% 
  filter(group == "B", abundance > 1000) %>%  
  ggplot(aes(x = genus, y = abundance))+
  geom_col()+ 
  coord_flip()
```

